import { BidSearchItemKeyType, BidSearchOptionalQueryType } from './types';

export const BidSearchQueryMap: Record<
  keyof BidSearchOptionalQueryType,
  string
> = {
  inqryDiv: '조회구분',
  inqryBgnDt: '조회시작일시',
  inqryEndDt: '조회종료일시',
  bidNtceNm: '입찰공고명',
  ntceInsttCd: '공고기관코드',
  ntceInsttNm: '공고기관명',
  dminsttCd: '수요기관코드',
  dminsttNm: '수요기관명',
  refNo: '참조번호',
  prtcptLmtRgnCd: '참가제한지역코드',
  prtcptLmtRgnNm: '참가제한지역명',
  indstrytyCd: '업종코드',
  indstrytyNm: '업종명',
  presmptPrceBgn: '추정가격시작',
  presmptPrceEnd: '추정가격종료',
  dtilPrdctClsfcNoNm: '세부품명번호',
  masYn: '다수공급경쟁자여부',
  prcrmntReqNo: '조달요청번호',
  bidClseExcpYn: '입찰마감제외여부',
  intrntnlDivCd: '국제입찰구분코드',
};

export const BidSearchItemKeyMap: Record<BidSearchItemKeyType, string> = {
  ntceInsttCd: '공고기관코드',
  ntceInsttNm: '공고기관명',
  dminsttCd: '수요기관코드',
  dminsttNm: '수요기관명',
  refNo: '참조번호',
  VAT: '부가가치세',
  arsltApplDocRcptDt: '실적신청서접수일시',
  arsltApplDocRcptMthdNm: '실적신청서접수방법명',
  arsltCmptYn: '실적경쟁여부',
  bdgtAmt: '예산금액',
  bfSpecRgstNo: '사전규격등록번호',
  bidBeginDt: '입찰개시일시',
  bidClseDt: '입찰마감일시',
  bidGrntymnyPaymntYn: '입찰보증금납부여부',
  bidMethdNm: '입찰방식명',
  bidNtceDt: '입찰공고일시',
  bidNtceDtlUrl: '입찰공고상세URL',
  bidNtceNo: '입찰공고번호',
  bidNtceOrd: '입찰공고차수',
  bidNtceNm: '입찰공고명',
  bidNtceUrl: '입찰공고URL',
  bidPrtcptFee: '입찰참가수수료',
  bidPrtcptFeePaymntYn: '입찰참가수수료납부여부',
  bidPrtcptLmtYn: '입찰참가제한여부',
  bidQlfctRgstDt: '입찰참가자격등록마감일시',
  brffcBidprcPermsnYn: '지사투찰허용여부',
  chgDt: '변경일시',
  chgNtceRsn: '변경공고사유',
  ciblAplYn: '건설산업법적용대상여부',
  cmmnSpldmdAgrmntClseDt: '공동수급협정마감일시',
  cmmnSpldmdAgrmntRcptdocMethd: '공동수급협정서접수방식',
  cmmnSpldmdCnum: '공동수급업체수',
  cmmnSpldmdCorpRgnLmtYn: '공동수급업체지역제한여부',
  cmmnSpldmdMethdCd: '공동수급방식코드',
  cmmnSpldmdMethdNm: '공동수급방식명',
  cnstrtnAbltyEvlAmtList: '시공능력평가금액목록',
  cnstrtsiteRgnNm: '공사현장지역명',
  cnsttyAccotShreRateList: '공종별지분율목록',
  cntrctCnclsMthdNm: '계약체결방법명',
  contrctrcnstrtnGovsplyMtrlAmt: '도급자설치관급자재금액',
  crdtrNm: '채권자명',
  d2bMngAssmntLwstlmtRt: '방사청관리사정하한율',
  d2bMngAssmntUplmtRt: '방사청관리사정상한율',
  d2bMngBfEvalClseDt: '방사청관리사전심사마감일시',
  d2bMngBfEvalObjYn: '방사청관리사전심사대상여부',
  d2bMngBssamt: '방사청관리기초금액',
  d2bMngCnstwkDivNm: '방사청관리공사구분명',
  d2bMngCnstwkLctNm: '방사청관리공사위치명',
  d2bMngCnstwkNo: '방사청관리공사번호',
  d2bMngCnstwkOutlnCntnts: '방사청관리공사개요내용',
  d2bMngCnstwkPrdCntnts: '방사청관리공사기간내용',
  d2bMngCnstwkScleCntnts: '방사청관리공사규모내용',
  d2bMngDmndYear: '방사청관리요구년도',
  d2bMngNgttnPlanDate: '방사청관리협상계획일자',
  d2bMngNgttnStleNm: '방사청관리협상형태명',
  d2bMngPblctPlceNm: '방사청관리게재장소명',
  d2bMngProgrsSttusNm: '방사청관리진행상태명',
  d2bMngRgnLmtYn: '방사청관리지역제한여부',
  d2bMngRgstEvalExmpYn: '방사청관리등록심사면제여부',
  d2bMngRsrvtnPrceBssAplYn: '방사청관리예비가격기초적용여부',
  dcmtgOprtnDt: '설명회실시일시',
  dcmtgOprtnPlce: '설명회실시장소',
  dminsttOfclEmailAdrs: '수요기관담당자이메일주소',
  drwtPrdprcNum: '추첨예가건수',
  dsgntCmptYn: '지명경쟁여부',
  dtlsBidYn: '내역입찰여부',
  exctvNm: '집행관명',
  govcnstrtnGovsplyMtrlAmt: '관급자설치관급자재금액',
  govsplyAmt: '관급금액',
  incntvRgnNm1: '가산지역명1',
  incntvRgnNm2: '가산지역명2',
  incntvRgnNm3: '가산지역명3',
  incntvRgnNm4: '가산지역명4',
  indstrytyEvlRt: '업종평가비율',
  indstrytyLmtYn: '업종제한여부',
  indutyVAT: '주공종부가가치세',
  intrbidYn: '국제입찰여부',
  jntcontrctDutyRgnNm1: '공동도급의무지역명1',
  jntcontrctDutyRgnNm2: '공동도급의무지역명2',
  jntcontrctDutyRgnNm3: '공동도급의무지역명3',
  linkInsttNm: '연계기관명',
  mainCnsttyCnstwkPrearngAmt: '주공종공사예정금액',
  mainCnsttyNm: '주공종명',
  mainCnsttyPresmptPrce: '주공종추정가격',
  mtltyAdvcPsblYn: '상호시장진출허용여부',
  mtltyAdvcPsblYnCnstwkNm: '건설산업법적용대상공사명',
  ntceDscrptYn: '공고설명여부',
  ntceInsttOfclNm: '공고기관담당자명',
  ntceInsttOfclEmailAdrs: '공고기관담당자이메일주소',
  ntceInsttOfclTelNo: '공고기관담당자전화번호',
  ntceKindNm: '공고종류명',
  ntceSpecDocUrl1: '공고규격서1 - URL',
  ntceSpecDocUrl2: '공고규격서2 - URL',
  ntceSpecDocUrl3: '공고규격서3 - URL',
  ntceSpecDocUrl4: '공고규격서4 - URL',
  ntceSpecDocUrl5: '공고규격서5 - URL',
  ntceSpecDocUrl6: '공고규격서6 - URL',
  ntceSpecDocUrl7: '공고규격서7 - URL',
  ntceSpecDocUrl8: '공고규격서8 - URL',
  ntceSpecDocUrl9: '공고규격서9 - URL',
  ntceSpecDocUrl10: '공고규격서10 - URL',
  ntceSpecFileNm1: '공고규격서1 - 파일명',
  ntceSpecFileNm2: '공고규격서2 - 파일명',
  ntceSpecFileNm3: '공고규격서3 - 파일명',
  ntceSpecFileNm4: '공고규격서4 - 파일명',
  ntceSpecFileNm5: '공고규격서5 - 파일명',
  ntceSpecFileNm6: '공고규격서6 - 파일명',
  ntceSpecFileNm7: '공고규격서7 - 파일명',
  ntceSpecFileNm8: '공고규격서8 - 파일명',
  ntceSpecFileNm9: '공고규격서9 - 파일명',
  ntceSpecFileNm10: '공고규격서10 - 파일명',
  opengDt: '개찰일시',
  opengPlce: '개찰장소',
  orderPlanUntyNo: '발주계획통합번호',
  pqApplDocRcptDt: 'PQ신청서접수일시',
  pqApplDocRcptMthdNm: 'PQ신청서접수방법명',
  pqEvalYn: 'PQ심사여부',
  prearngPrceDcsnMthdNm: '예정가격결정방법명',
  presmptPrce: '추정가격',
  rbidOpengDt: '재입찰개찰일시',
  rbidPermsnYn: '재입찰허용여부',
  reNtceYn: '재공고여부',
  rgnDutyJntcontrctRt: '지역의무공동도급비율',
  rgnDutyJntcontrctYn: '지역의무공동도급여부',
  rgstDt: '등록일시',
  rgstTyNm: '입찰공고가',
  rsrvtnPrceReMkngMthdNm: '예비가격재작성방법명',
  sptDscrptDocUrl1: '현장설명서1 - URL',
  sptDscrptDocUrl2: '현장설명서2 - URL',
  sptDscrptDocUrl3: '현장설명서3 - URL',
  sptDscrptDocUrl4: '현장설명서4 - URL',
  sptDscrptDocUrl5: '현장설명서5 - URL',
  stdNtceDocUrl: '표준공고서URL',
  subsiCnsttyIndstrytyEvlRt1: '부공종업종평가비율1',
  subsiCnsttyIndstrytyEvlRt2: '부공종업종평가비율2',
  subsiCnsttyIndstrytyEvlRt3: '부공종업종평가비율3',
  subsiCnsttyIndstrytyEvlRt4: '부공종업종평가비율4',
  subsiCnsttyIndstrytyEvlRt5: '부공종업종평가비율5',
  subsiCnsttyIndstrytyEvlRt6: '부공종업종평가비율6',
  subsiCnsttyIndstrytyEvlRt7: '부공종업종평가비율7',
  subsiCnsttyIndstrytyEvlRt8: '부공종업종평가비율8',
  subsiCnsttyIndstrytyEvlRt9: '부공종업종평가비율9',
  subsiCnsttyNm1: '부대공종명1',
  subsiCnsttyNm2: '부대공종명2',
  subsiCnsttyNm3: '부대공종명3',
  subsiCnsttyNm4: '부대공종명4',
  subsiCnsttyNm5: '부대공종명5',
  subsiCnsttyNm6: '부대공종명6',
  subsiCnsttyNm7: '부대공종명7',
  subsiCnsttyNm8: '부대공종명8',
  subsiCnsttyNm9: '부대공종명9',
  sucsfbidLwltRate: '낙찰하한율',
  sucsfbidMthdCd: '낙찰방법코드',
  sucsfbidMthdNm: '낙찰방법명',
  totPrdprcNum: '총예가건수',
  untyNtceNo: '통합공고번호',
};
